require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/**/*
    - db/migrate/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - db/schema.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Gemfile
    - Rakefile

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/environments/*.rb
    - config/routes.rb

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/BlockForwarding:
  EnforcedStyle: explicit

Naming/InclusiveLanguage:
  Enabled: true

Naming/MethodParameterName:
  AllowedNames: [cc, id, to]

Style/ArrayCoercion:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Rails/ActionControllerFlashBeforeRender:
  Enabled: false

Rails/ActionOrder:
  ExpectedOrder: [index, show, new, create, edit, update, destroy]

Rails/EnvironmentVariableAccess:
  Enabled: true

Rails/SkipsModelValidations:
  AllowedMethods: ["insert_all!"]

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NestedGroups:
  Max: 5
